language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
cache: yarn
script: yarn test
after_script: "yarn coverage"
